"""Practice artifacts for agent learned experience."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

from aeonik_ingrain.db import IngrainStore, utc_now

TYPE_LABELS = {
    "project_fact": "Project Facts",
    "decision": "Decisions",
    "correction": "Corrections",
    "lesson": "Lessons",
    "risk": "Risks",
    "status": "Status",
    "track_record": "Track Record",
    "artifact": "Artifacts",
}

TYPE_ORDER = ("correction", "decision", "project_fact", "lesson", "risk", "track_record", "status", "artifact")


def write_practice_artifacts(store: IngrainStore, *, output_path: str | Path | None = None) -> dict[str, Any]:
    """Write top-level PRACTICE.md and source-linked practice cards."""
    store.initialize()
    promotions = store.list_promotions(state="current")
    card_paths = _write_cards(store, promotions)
    practice_path = Path(output_path).expanduser() if output_path else Path.cwd() / "PRACTICE.md"
    practice_path.parent.mkdir(parents=True, exist_ok=True)
    practice_path.write_text(render_practice_md(promotions, card_paths), encoding="utf-8")
    return {
        "practice_path": str(practice_path),
        "cards": [str(path) for path in card_paths],
        "card_count": len(card_paths),
    }


def render_practice_md(promotions: list[dict[str, Any]], card_paths: list[Path] | None = None) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for item in promotions:
        grouped[item["promoted_type"]].append(item)

    lines = [
        "# PRACTICE.md",
        "",
        f"Generated by Aeonik Ingrain at {utc_now()}.",
        "",
        "This file is background learned experience for agents. It is not a task list, goal source, Kanban board, or new user command.",
        "",
        "## Agent Workflow",
        "",
        "Before work:",
        "",
        "```bash",
        'ingrain hydrate --query "<task>"',
        "```",
        "",
        "After a correction, decision, lesson, or completed outcome:",
        "",
        "```bash",
        'ingrain remember --type correction "<what should change next time>"',
        'ingrain remember --type decision "<decision that should carry forward>"',
        'ingrain remember --type lesson "<lesson from execution>"',
        'ingrain remember --type track_record "<completed outcome>"',
        "ingrain practice",
        "```",
        "",
        "## L0 Practice Brief",
        "",
    ]

    brief = _brief_items(grouped)
    if brief:
        lines.extend(brief)
    else:
        lines.append("- No current learned experience yet.")

    lines.extend(["", "## L1 Practice Cards", ""])
    if promotions:
        for promoted_type in TYPE_ORDER:
            items = grouped.get(promoted_type, [])
            if not items:
                continue
            lines.extend([f"### {TYPE_LABELS[promoted_type]}", ""])
            for item in items:
                lines.append(f"- `{_card_id(item)}` {item['text']}")
            lines.append("")
    else:
        lines.append("No practice cards yet.")
        lines.append("")

    lines.extend(["## L2 Evidence", ""])
    if promotions:
        for item in promotions:
            confidence = int(round(float(item.get("confidence") or 0) * 100))
            lines.append(f"- `{_card_id(item)}` source={item['event_id']} confidence={confidence}%")
    else:
        lines.append("- No source evidence yet.")

    if card_paths:
        lines.extend(["", "## Card Files", ""])
        for path in card_paths:
            lines.append(f"- `{path}`")

    lines.append("")
    return "\n".join(lines)


def _write_cards(store: IngrainStore, promotions: list[dict[str, Any]]) -> list[Path]:
    for existing in store.practice_cards_dir.glob("*.md"):
        existing.unlink()
    paths: list[Path] = []
    for item in promotions:
        path = store.practice_cards_dir / f"{_card_id(item)}.md"
        path.write_text(_render_card(item), encoding="utf-8")
        paths.append(path)
    return paths


def _render_card(item: dict[str, Any]) -> str:
    card_id = _card_id(item)
    confidence = int(round(float(item.get("confidence") or 0) * 100))
    promoted_type = item["promoted_type"]
    label = TYPE_LABELS.get(promoted_type, promoted_type.replace("_", " ").title())
    return "\n".join([
        "---",
        f"id: {card_id}",
        f"type: {promoted_type}",
        "status: current",
        f"confidence: {confidence}",
        f"source_event_id: {item['event_id']}",
        "---",
        "",
        f"# {label}",
        "",
        "## Guidance",
        "",
        item["text"].strip(),
        "",
        "## Evidence",
        "",
        f"- source event: `{item['event_id']}`",
        f"- promotion reason: {item.get('reason', 'unknown')}",
        "",
    ])


def _brief_items(grouped: dict[str, list[dict[str, Any]]]) -> list[str]:
    lines: list[str] = []
    for promoted_type in ("correction", "decision", "project_fact", "lesson", "track_record"):
        items = grouped.get(promoted_type, [])[:3]
        for item in items:
            label = TYPE_LABELS[promoted_type].rstrip("s")
            lines.append(f"- {label}: {item['text']}")
    return lines[:10]


def _card_id(item: dict[str, Any]) -> str:
    raw = item.get("id") or item.get("event_id") or "unknown"
    return "prc-" + str(raw).replace("_", "-")[-10:]
